### ISSUE TITLE
Supporto multilingue

### ISSUE THREAD

**Issue by PorfirioTramontana** [matteocaiazzo/APPLICAZIONEESAME#2]
Manca il supporto all'internazionalizzazione: in particolare molti testi sono scritti direttamente nel codice.

**Comment by matteocaiazzo** [comment]
aggiunto da Riccardo il supporto multilingua in inglese e portoghese (abbiamo voluto strafare)

**Comment by PorfirioTramontana** [comment]
Tanto il portoghese non (si) paga mai!
