### ISSUE TITLE
Elenco di luoghi cablato

### ISSUE THREAD

**Issue by PorfirioTramontana** [matteocaiazzo/APPLICAZIONEESAME#3]
L'elenco dei luoghi è cablato (scritto direttamente) all'interno dell'applicazione, rendendo impossibile aggiungerne altri senza ricompilare l'applicazione.
Si potrebbe spostarlo su di una risorsa esterna (ad esempio file json pubblicato su qualche spazio).

**Comment by PorfirioTramontana** [comment]
L'elenco bloccato dei luoghi riguarda chiaramente anche i segnaposti sulle mappe

**Comment by matteocaiazzo** [comment]
Siamo riusciti a popolare lo spinner dei luoghi tramite file json (host su altervista). Al momento non siamo riusciti a caricare i textview in modo dinamico .

**Comment by PorfirioTramontana** [comment]
Secondo me GoodModel deve diventare una classe dove tutti i campi sono delle ArrayList che possono contenere tutti i possibili valori, anzichè delle semplici stringhe che contengono il valore in quel momento selezionato.

**Comment by matteocaiazzo** [comment]
Sono riuscito a rendere la classe completamente dinamica (prendo tutti i dati dal json caricato su altervista). Ho effettuato il testing e funziona quindi si puo chiudere la issue! :)

**Comment by PorfirioTramontana** [comment]
OK, funziona.

Solo una domanda: perchè il file su server è php invece che direttamente json?

**Comment by matteocaiazzo** [comment]
ci è risultato più semplice operare direttamente col php (abbiamo un associazione label valore più immediata)
