### ISSUE TITLE
Problemi con le mappe

### ISSUE THREAD

**Issue by PorfirioTramontana** [matteocaiazzo/APPLICAZIONEESAME#4]
Ricompilando, non riesco più a vedere le mappe.
Probabilmente dovete aggiungere il mio SHA-1 da sviluppatore nell'elenco di quelli consentiti sulla console delle API di Google. Il mio SHA-1 è:

SHA1: 59:BC:1A:1E:89:81:EF:23:F5:D9:DD:47:CA:8E:79:D7:59:43:52:97

**Comment by matteocaiazzo** [comment]
Aggiunta la SHA-1 da lei inviata alla console google,aspettiamo riscontri

**Comment by PorfirioTramontana** [comment]
Ora funziona!
