### ISSUE TITLE
Aggiornamento contapassi

### ISSUE THREAD

**Issue by PorfirioTramontana** [matteocaiazzo/APPLICAZIONEESAME#6]
Non ho capito come si aggiorna il contapassi e come avete settato la sua sensibilità.

In particolare, provando su dispositivo il conteggio dei passi (139) rimane sempre lo stesso, anche aprendo e chiudendo l'activity o l'app (e agitando il dispositivo).

**Comment by matteocaiazzo** [comment]
Ho aumentato la sensibilita del dispositivo settando SENSOR_DELAY ad un valore FASTEST. Effettuando un test dalla mia camera alla sala , a fronte di 20 passi effettuati ne ha registrati 19.  Sul mio dispositivo agitando il telefono i passi vengono conteggiati

**Comment by PorfirioTramontana** [comment]
Effettivamente ho verificato che sul mio telefono ci sono problemi col contapassi anche quando lo utilizza per Google Fit. Chiaramente non ho fatto prove di questo tipo con l'emulatore.
Spero che non mi abbiate buggato il contapassi, in qualche modo !

**Comment by matteocaiazzo** [comment]
Prof le abbiamo installato un malware senza che se ne accorgesse. Dobbiamo ringraziare il prof di sicurezza per le conoscenze da hacker acquisite
